const resList = [
  {
    data: {
      cards: [
        {
          card: {
            "@type":
              "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
            id: "317552",
            name: "Home Food Co.",
            cloudinaryImageId:
              "FOOD_CATALOG/IMAGES/CMS/2025/2/21/efb2ad6f-b925-42cf-a149-18e88354b678_7a86fcd7-7ff5-4c46-ae35-912af4972715.jpeg",
            locality: "Nadia",
            areaName: "Kalyani",
            costForTwo: "₹250 for two",
            cuisines: ["North Indian", "Bengali", "Chinese", "Biryani"],
            avgRating: 4,
            parentId: "96482",
            avgRatingString: "4.0",
            totalRatingsString: "1.0K+",
            deliveryTime: 31,
            lastMileTravel: 3.7,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "3.7 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
        {
          card: {
            "@type":
              "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
            id: "697200",
            name: "Baba Briyani",
            cloudinaryImageId: "f764e350478ca4f7c7054eaeeea19fc7",
            locality: "Lenin sarani",
            areaName: "Kalyani",
            costForTwo: "₹143 for two",
            cuisines: ["Biryani", "North Indian"],
            avgRating: 3.9,
            parentId: "416954",
            avgRatingString: "3.9",
            totalRatingsString: "34",
            deliveryTime: 31,
            lastMileTravel: 1.5,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "1.5 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
        {
          card: {
            "@type":
              "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
            id: "200594",
            name: "Raj Cabin",
            cloudinaryImageId: "zwwck9sd8vg4zzgppw3w",
            locality: "Narendrapur",
            areaName: "Naihati",
            costForTwo: "₹300 for two",
            cuisines: [
              "Biryani",
              "Indian",
              "South Indian",
              "Tandoor",
              "Chinese",
            ],
            avgRating: 4.1,
            parentId: "164912",
            avgRatingString: "4.1",
            totalRatingsString: "36K+",
            promoted: true,
            deliveryTime: 34,
            lastMileTravel: 10.7,
            serviceability: "SERVICEABLE",
            slaString: "30-35 mins",
            lastMileTravelString: "10.7 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
        {
          card: {
            "@type":
              "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
            id: "168720",
            name: "Shiv Hotel",
            cloudinaryImageId: "zyhx9f3pzdeviqvayaeu",
            locality: "Thana Mor",
            areaName: "Kanchrapara Loco",
            costForTwo: "₹200 for two",
            cuisines: ["Chinese", "North Indian", "Tandoor"],
            avgRating: 3.7,
            parentId: "183234",
            avgRatingString: "3.7",
            totalRatingsString: "1.5K+",
            deliveryTime: 38,
            lastMileTravel: 1.3,
            serviceability: "SERVICEABLE",
            slaString: "35-40 mins",
            lastMileTravelString: "1.3 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
        {
          card: {
            "@type":
              "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
            id: "213772",
            name: "New Raj Cabin (Jitu)",
            cloudinaryImageId:
              "FOOD_CATALOG/IMAGES/CMS/2024/6/25/7063ca7c-d3bb-4d6a-8bbc-72357c0d42ea_dd8dc75a-3561-446b-b545-e315c5d337fb.jpg",
            locality: "Natun Bazar",
            areaName: "Naihati",
            costForTwo: "₹300 for two",
            cuisines: ["Biryani", "Indian", "South Indian", "Chinese"],
            avgRating: 3.7,
            parentId: "147662",
            avgRatingString: "3.7",
            totalRatingsString: "5.1K+",
            promoted: true,
            deliveryTime: 38,
            lastMileTravel: 10.7,
            serviceability: "SERVICEABLE",
            slaString: "35-40 mins",
            lastMileTravelString: "10.7 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
        {
          card: {
            "@type":
              "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
            id: "303893",
            name: "Haji Biryani House",
            cloudinaryImageId: "dcv3qx56pmeq12a0nage",
            locality: "Kalyani",
            areaName: "Kalyani",
            costForTwo: "₹350 for two",
            cuisines: ["Biryani", "Mughlai", "Indian"],
            avgRating: 3.8,
            parentId: "18592",
            avgRatingString: "3.8",
            totalRatingsString: "2.4K+",
            deliveryTime: 15,
            lastMileTravel: 1.5,
            serviceability: "SERVICEABLE",
            slaString: "15-20 mins",
            lastMileTravelString: "1.5 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
        {
          card: {
            "@type":
              "type.googleapis.com/swiggy.presentation.food.v2.Restaurant",
            id: "889768",
            name: "MITRA BIRYANI",
            cloudinaryImageId:
              "FOOD_CATALOG/IMAGES/CMS/2024/6/6/ba887291-da22-415b-8230-7487d0c6be83_778cf69a-dce7-4929-9cb1-aa4038524bc8.jpg",
            locality: "Kanchrapara,",
            areaName: "Halisahar",
            costForTwo: "₹600 for two",
            cuisines: ["Biryani", "Desserts", "Kebabs", "Snacks"],
            avgRating: 3.6,
            parentId: "520126",
            avgRatingString: "3.6",
            totalRatingsString: "54",
            promoted: true,
            deliveryTime: 23,
            lastMileTravel: 2.4,
            serviceability: "SERVICEABLE",
            slaString: "20-25 mins",
            lastMileTravelString: "2.4 km",
            iconType: "ICON_TYPE_EMPTY",
          },
        },
        // Additional restaurant cards can be added here...
      ],
    },
  },
];

export default resList;
